### ISSUE TITLE
LCD board connector no longer available from link

### ISSUE THREAD

**Issue by Q-Bert-Reynolds** [kamicane/Super-DMG-01#2]
[The LCD connector Ali Express link in the build of materials](https://github.com/kamicane/Super-DMG-01/blob/e557c3cb3f4540ce3f1007be29782819fd7b3acc/super-dmg-cpu/README.md?plain=1#L52) is dead. Almost felt like I caused it. It wasn't dead until after I ordered a few and nothing came. I've been looking for another source, but I've had no such luck.

**Comment by Q-Bert-Reynolds** [comment]
I found a potentially suitable replacement for the [LCD board connector here](https://www.aliexpress.us/item/3256805298523011.html). They have an option for a 21 pin FPC connector with 1.25mm spacing that looks the part. I'm ordering a few now. I'll let you know how it goes.

On a related note, I found an okay-ish replacement for the [power switch from Mouser](https://www.mouser.com/ProductDetail/CK/SK22F02G6?qs=Gufeu08L/l3k5gmurXhV/g%3D%3D). It has the same footprint, but it requires quite a bit of trimming to fit - removing two of the pins, shortening the metal housing by 3mm or so, and shaving down the plastic slide so that it can fit in the switch cover plate thing. Still looking for a low profile version though.

**Comment by kamicane** [comment]
> I found a potentially suitable replacement for the [LCD board connector here](https://www.aliexpress.us/item/3256805298523011.html). They have an option for a 21 pin FPC connector with 1.25mm spacing that looks the part. I'm ordering a few now. I'll let you know how it goes.

Amazing!

As for the power switch another idea could be finding a smaller one and making a 3d printed replacement part to fit it in the shell. Should be fine as long as it lines up somewhat.

**Comment by Q-Bert-Reynolds** [comment]
Completely forgot to follow up. I can confirm that the connector they sent fits and works.

**Comment by kamicane** [comment]
Updated the link, thanks!

**Comment by explit28** [comment]
Unfortunately they don't ship to Germany, maybe to some other countries also.
 https://www.aliexpress.us/item/3256805298523011.html

If you find another seller, who sells the display connector - it would be really cool!

**Comment by itavero** [comment]
@explit7 Did you find a supplier yet? Also looking for these and the provided links do not work for me in the Netherlands.

**Comment by explit28** [comment]
> @explit7 Did you find a supplier yet? Also looking for these and the provided links do not work for me in the Netherlands.

Unfortunately not. I had to sacrifice a Mainboard in bad condition. for me the links also not work anymore... :(
