### ISSUE TITLE
audio amplifier assembly on original dmg

### ISSUE THREAD

**Issue by Neorad1870** [kamicane/Super-DMG-01#3]
hello, would it be possible to have a photo of the assembly concerning the audio amplifier on an original dmg, I do not fully understand the explanations, thank you

**Comment by kamicane** [comment]
![image](https://github.com/kamicane/Super-DMG-01/assets/7131/eb0acf78-64c7-4012-9ed0-1d85c31218bd)

Install only the circled components and keep the speaker in the LCD board. Make sure to solder the power cable as well. That's it.
